colors:
  body: none
  date: magenta
  tags: red
  title: green
default_hour: 9
default_minute: 0
editor: nvim
encrypt: false
highlight: true
indent_character: '|'
journals:
  default:
    journal: ~/journals/sourceability.txt
    encrypt: true
  personal:
    journal: ~/journals/journal.txt
linewrap: 80
tagsymbols: '@'
template: false
timeformat: '%Y-%m-%d %H:%M'
version: v2.4.5
