# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="lambda"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
export UPDATE_ZSH_DAYS=14

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="false"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
# With autosuggestions
#plugins=(emoji gitfast vim venv hg mercurial docker-compose zsh-autosuggestions brew asdf composer docker tmuxinator)
# Without autosuggestions
plugins=(emoji gitfast vim-interaction virtualenv mercurial docker-compose asdf composer docker fzf mix)

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"
export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

# Include environment specific config if file is readable
if [ -r ~/.zshrc.local-theme ]; then
  source ~/.zshrc.local-theme
fi

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
alias p="pacaur"
alias pm="pacman"
alias vim="nvim"
alias vi="nvim"
alias t="todo.sh"
alias ag="ag --color --pager='less -R'"
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias ls="ls -h"
alias nq="nix-env -qaP"
alias ni="nix-env -i"
alias nl="nix-env -q"
alias c='xclip -selection clipboard'
alias v='xclip -o'

archive-folder() {
  if [[ -z "$1" ]]; then
    echo "Missing folder to archive"
    return
  fi

  local folder_name="$1"
  local gzip_file="$folder_name-$(date +%Y-%m-%d).tar.gz"
  echo "gziping folder"
  tar -czf "$gzip_file" "$folder_name"
  ls -havl "$gzip_file"
  echo -n "Delete folder $folder_name? [y/n] "
  read delete_response

  if [[ "$delete_response" == "y" ]] || [[ "$delete_response" == "Y" ]]; then
    echo "Deleting $folder_name..."
    sleep 5
    rm -r "$folder_name"
  else
    echo "Skipping file deletion"
    return
  fi
}

dirsize(){
  du -cxh -d 1 | sort -h
}

source "$HOME/.cargo/env"
export EDITOR="nvim"
export VISUAL="nvim"
export LESS="-R"
export NODE_PATH=/usr/lib/nodejs:/usr/lib/node_modules:/usr/share/javascript:/usr/local/lib/node_modules
export MANPATH="$HOME/.linuxbrew/share/man:$MANPATH"
export INFOPATH="$HOME/.linuxbrew/share/info:$INFOPATH"
export PYENV_ROOT="$HOME/.pyenv"
export RIPGREP_CONFIG_PATH="$HOME/.rgrc"
export FZF_DEFAULT_COMMAND='rg --files --hidden --follow --color=never --glob="!**/.git/"'
export PATH=/usr/local/go/bin:$PATH
export PATH=$HOME/go/bin:$PATH
export PATH=$HOME/.cargo/bin:$PATH
export PATH=$HOME/.linuxbrew/bin:$PATH
export PATH=$HOME/.config/composer/vendor/bin:$PATH
export PATH=/usr/local/heroku/bin:$PATH
export PATH=/usr/lib64/qt-3.3/bin:$PATH
export PATH=/usr/bin:$PATH
export PATH=/usr/local/bin:$PATH
export PATH=/usr/local/sbin:$PATH
export PATH=/usr/sbin:$PATH
export PATH=$HOME/.npm/bin:$PATH
export PATH=$HOME/.npm-packages/bin:$PATH
export PATH=$HOME/.bin:$HOME/bin:$PATH
export PATH=$HOME/.local/bin:$PATH
export PATH=$HOME/.asdf/installs/haskell/8.6.5/bin:$PATH
export PATH="/usr/local/opt/mysql-client/bin:$PATH"
export QT_SELECT=5
export PROMPT="%(?:$emoji[smiling_face_with_sunglasses]:$emoji[fire])  $PROMPT"

# Save lots of history
export HISTSIZE=50000
export SAVEHIST=50000
export HISTFILE=$HOME/.zsh_history
# Save every command before execution, read the hist file
setopt sharehistory

# Add this to your zshrc or bzshrc file
_not_inside_tmux() { [[ -z "$TMUX" ]] }
_not_in_vscode() { [[ $TERM_PROGRAM != "vscode" ]] }
_not_in_intellij() { [[ $TERMINAL_EMULATOR != "JetBrains-JediTerm" ]] }

ensure_tmux_is_running() {
  if _not_inside_tmux && _not_in_vscode && _not_in_intellij; then
    tat
  fi
}

ensure_tmux_is_running

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Include environment specific config if file is readable
if [ -r ~/.zshrc.local ]; then
  source ~/.zshrc.local
fi

if [ $TILIX_ID ] || [ $VTE_VERSION ]; then
        source /etc/profile.d/vte.sh
fi
